
server:
  port: 8083
  servlet:
    context-path: /user


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user
    username: user
    password: user
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect